### ISSUE TITLE
Add a duplicate church actor with $500 crate.

### ISSUE THREAD

**Issue by SoScared** [RAunplugged/uRA#22]
Not terribly important but the $500 church crate bonus was something memorable in the original campaigns. Why not add it as a standard actor in the editor and give map makers quick access to a $500 loot church.

**Comment by BlackenedRA** [comment]
This was simple enough for me to caveman my way through it. So I've created the neccessary changes. But as far as creating a PR and stuff I'd need a walk through on how to properly do that :)

**Comment by SoScared** [comment]
Added with commit: https://github.com/RAunplugged/uRA/commit/ea71fba9ece5e16d15e71bfa3b3e7e26cb5e2199
