### ISSUE TITLE
Map test failure on Linux originating from ura|rules/ai/ai-brutal.yaml line 648

### ISSUE THREAD

**Issue by fusion809** [RAunplugged/uRA#48]
Hi,

Presently on Linux (specifically CentOS, Fedora and openSUSE) tests fail with the log: https://paste.pound-python.org/show/yUZssGqkRBvT7f2QaToP/. Specifically commit 70c4d7dec124f6c8d0167bdda594b3a135ce8a09 fails in this regard.

Thanks for your time,
Brenton

**Comment by SoScared** [comment]
Sorry for the late reply, this error should have resolved itself with commits https://github.com/RAunplugged/uRA/commit/22ec914d8559c986860bbb052daa6f3515e3f14b and https://github.com/RAunplugged/uRA/commit/55bab44a8c7d409170331ea95e10a8101c292447

**Comment by fusion809** [comment]
Yep you're right all is good now, it's passing its tests.
