### ISSUE TITLE
TypeDictionary contains multiple instances of type `OpenRA.Mods.Common.Traits.CapturesInfo`

### ISSUE THREAD

**Issue by fusion809** [RAunplugged/uRA#51]
Hi,

On openSUSE Tumbleweed commit 373 (80da3e1c6ebec5299efa5e9cca841f472f56de10) when built as an AppImage crashed, after a little gameplay on Bombardment Islands, with two teams of three players (with the other five players being AIs) all randomly assigned. I think I was ordering the moving of an engineer, or maybe creating a new War Factory or something (it happened quite unexpectedly, so I wasn't paying too much attention). Here's my logs (beware I did look at the replay before uploading these logs, so some of them may have been modified by me watching the replay):

[exception-2018-11-04T173038Z.log](https://github.com/RAunplugged/uRA/files/2546105/exception-2018-11-04T173038Z.log)
[debug.log](https://github.com/RAunplugged/uRA/files/2546106/debug.log)
[perf.log](https://github.com/RAunplugged/uRA/files/2546107/perf.log)
[server.log](https://github.com/RAunplugged/uRA/files/2546108/server.log)

my replay is in this zip archive: 
[Unplugged-exception-replay-20181105.orarep.zip](https://github.com/RAunplugged/uRA/files/2546109/Unplugged-exception-replay-20181105.orarep.zip)

My version of Mono is 5.10.1.47, and my version of Lua is 5.1.5. 

Thanks for your time,
Brenton

**Comment by SoScared** [comment]
Hey!

This crash was caused by an error with the new engineer cap overhaul in the bleed.

Fortunately this is a known bug and should now be fixed with the mod and engine fork update, merged just minutes ago.

related issue: https://github.com/OpenRA/OpenRA/issues/15697

**Comment by SoScared** [comment]
Could you check on the fix for good measure?

**Comment by fusion809** [comment]
I just played a game with commit 376 (e03912bd378eb209d21d00af9a45109053aecde6), with plenty of engineers and so far no crash, so it does appear to be fixed, thanks.
